
--New Schema
CREATE TABLE IF NOT EXISTS kiosk_locale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    abbrev VARCHAR(10),
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS rich_text_long_description_field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(800),
    page_container INTEGER
);

CREATE TABLE IF NOT EXISTS field_container (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_container_name VARCHAR(100),
    has_nested_container BOOLEAN,
    has_container_parent BOOLEAN,
    parent INTEGER
);

CREATE TABLE IF NOT EXISTS page_internals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale INTEGER REFERENCES kiosk_locale(id),
    created_on DATE,
    last_modified TIMESTAMP,
    page_status VARCHAR(50),
    page INTEGER
);

CREATE TABLE IF NOT EXISTS page_title_field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(100),
    page INTEGER
);

CREATE TABLE IF NOT EXISTS page (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_type VARCHAR(50),
    page_name VARCHAR(100)
);
