CREATE TABLE IF NOT EXISTS kiosk_locale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    abbrev VARCHAR(10),
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS page_metadata (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on DATE,
    last_modified TIMESTAMP,
    page_status VARCHAR(50),
    kiosk_page_internals INTEGER
);

CREATE TABLE IF NOT EXISTS kiosk_page_internals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale INTEGER REFERENCES kiosk_locale(id),
    about_page INTEGER
);

CREATE TABLE IF NOT EXISTS r_description_field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(800),
    about_page INTEGER
);

CREATE TABLE IF NOT EXISTS Image (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR(50),
    width INTEGER,
    height INTEGER,
    image_field INTEGER
);

CREATE TABLE IF NOT EXISTS alternate_text_field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(100),
    image_field INTEGER
);

CREATE TABLE IF NOT EXISTS image_field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    about_page INTEGER
);

CREATE TABLE IF NOT EXISTS page_title_field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(100),
    about_page INTEGER
);

CREATE TABLE IF NOT EXISTS about_page (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS url_field {
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(100),
    error_404_page INTEGER
}

CREATE TABLE IF NOT EXISTS display_text_field {
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(50),
    error_404_page INTEGER
}

CREATE TABLE IF NOT EXISTS simple_description_field {
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name VARCHAR(50),
    field_value VARCHAR(200),
    error_404_page INTEGER
}

CREATE TABLE IF NOT EXISTS error_404_page {
    
}
